name: Validação Segura

on:
  push:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    
    steps:
    - name: Checkout (versão segura)
      uses: actions/checkout@v4
      
    - name: Validar arquivos básicos
      run: |
        echo "✅ Validação básica concluída"
        echo "Arquivos modificados:"
        git diff --name-only HEAD~1
