name: Update Deployment Status

on:
  push:
    branches:
      - main
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  update-deployment-status:
    runs-on: ubuntu-latest
    if: ${{ always() }}  # Executa sempre, para capturar sucesso ou falha
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update deployment status (success)
        if: success()
        uses: chrnorm/deployment-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: production
          environment-url: ${{ secrets.JIRA_URL }}  # Use uma variável secreta para a URL
          deployment-id: ${{ steps.deployment.outputs.deployment-id }}
          state: 'success'

      - name: Update deployment status (failure)
        if: failure()
        uses: chrnorm/deployment-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: production
          environment-url: ${{ secrets.JIRA_URL }}  # Use uma variável secreta para a URL
          deployment-id: ${{ steps.deployment.outputs.deployment-id }}
          state: 'failure'
